In [1]:
import pandas as pd
import numpy as np
import rasterio
import geopandas as gpd
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
mlr_result = pd.read_csv('/home/GermanCitiesSUHI/data/results/final_mlr_results.csv', index_col=[0,1])
vif_result = pd.read_csv('/home/GermanCitiesSUHI/data/results/final_mlr_results_vif.csv', index_col=[0,1])

In [3]:
mlr_result

,,Zone_15,Zone_26,Global.1,Zone_15.1,Zone_26.1,Global.2,Zone_15.2,Zone_26.2,Global.3,Zone_15.3,Zone_26.3,Global.4,Zone_15.4,Zone_26.4
Subset_Scale,Global,,,,,,,,,,,,,,
Grid_Resolution,100m,100m,100m,250m,250m,250m,500m,500m,500m,750m,750m,750m,1000m,1000m,1000m
const,2.617,2.459,2.929,2.537,2.382,2.843,2.412,2.264,2.702,2.259,2.115,2.540,2.187,2.037,2.479
PLAND_tree_cover,-1.802***,-1.730***,-1.832***,-3.010***,-2.979***,-2.995***,-2.989***,-2.898***,-2.996***,-2.776***,-2.693***,-2.841***,-2.619***,-2.507***,-2.633***
building_height_mean,0.604***,0.639***,0.619***,0.300***,0.338***,0.295***,0.182***,0.270***,0.227***,0.272***,0.337***,0.272***,0.301***,0.371***,0.375***
pop_sum,-0.149***,-0.150***,-0.204***,-0.037***,0.004,-0.121***,-0.028*,0.028,-0.090***,0.021,0.064**,-0.063*,0.042*,0.097***,-0.062
ED_tree_cover,0.260***,0.240***,0.321***,0.281***,0.254***,0.365***,0.281***,0.313***,0.503***,0.424***,0.397***,0.544***,0.462***,0.390***,0.632***
BCR,0.420***,0.533***,0.278***,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTAG,0.137***,0.140***,0.139***,0.159***,0.145***,0.197***,0.088***,0.112***,0.197***,0.090***,0.073***,0.146***,0.121***,0.069**,0.234***
ED_bare_land,nan,NaN,NaN,NaN,NaN,NaN,-0.014,0.013,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ED_cropland,0.037***,0.018***,0.089***,-0.068***,-0.110***,0.049**,-0.192***,-0.266***,-0.015,NaN,NaN,NaN,NaN,NaN,NaN
ED_grassland,-0.031***,0.010*,-0.097***,-0.246***,-0.189***,-0.335***,-0.392***,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ED_water,0.161***,0.161***,0.168***,-0.038***,-0.046***,-0.002,-0.142***,-0.153***,-0.016,-0.063***,-0.099***,0.020,-0.128***,-0.187***,0.012
ED_wetland,-0.003,-0.003,NaN,NaN,NaN,-0.012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LPI_bare_land,0.015***,0.037***,-0.019***,-0.030***,-0.006,-0.063***,-0.023,0.000,-0.054***,-0.044***,0.028,-0.110***,-0.003,0.029,-0.031
LPI_cropland,-0.326***,-0.298***,-0.315***,-0.986***,-0.968***,-0.987***,-0.992***,-0.902***,-1.016***,-0.978***,-0.944***,-0.969***,-0.889***,-0.833***,-0.893***
LPI_grassland,-0.240***,-0.227***,-0.214***,-0.727***,-0.742***,-0.674***,-0.629***,-0.721***,-0.725***,-0.603***,-0.560***,-0.621***,-0.571***,-0.539***,-0.544***
LPI_shrubland,0.005*,NaN,NaN,0.010*,0.013*,NaN,0.002,NaN,-0.002,-0.003,-0.005,-0.001,0.002,-0.001,-0.031
LPI_water,-1.108***,-1.099***,-1.073***,-1.645***,-1.689***,-1.517***,-1.561***,-1.546***,-1.448***,-1.390***,-1.355***,-1.369***,-1.240***,-1.228***,-1.140***
LPI_wetland,-0.062***,-0.042***,-0.085***,-0.093***,-0.060***,-0.118***,-0.085***,-0.046***,-0.080***,-0.058***,-0.043**,-0.037,-0.050**,-0.066***,0.021
LSI_bare_land,nan,NaN,NaN,-0.010,NaN,-0.054**,0.010,-0.015,NaN,0.103***,0.070**,0.061,NaN,NaN,-0.083
LSI_cropland,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.014,-0.098***,0.167***,0.018,-0.065*,0.156***
LSI_grassland,nan,NaN,NaN,NaN,NaN,NaN,NaN,-0.045*,NaN,-0.200***,-0.104***,-0.323***,-0.199***,-0.084*,NaN
LSI_shrubland,nan,NaN,NaN,NaN,NaN,NaN,0.008,0.014,NaN,-0.004,0.001,NaN,-0.009,0.003,NaN
LSI_water,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.081**,0.103**,NaN
LSI_wetland,nan,NaN,NaN,NaN,NaN,NaN,NaN,-0.028,-0.145***,NaN,NaN,-0.165***,-0.159***,NaN,-0.253***
PD_bare_land,0.010***,0.011***,0.002,-0.014,-0.026***,0.020,NaN,NaN,0.000,-0.028,-0.011,-0.024,0.076***,0.076***,0.102*
PD_built_up,0.274***,0.279***,0.225***,0.377***,0.389***,0.308***,0.327***,0.317***,0.206***,0.207***,0.208***,0.135***,0.155***,0.173***,0.051
PD_cropland,0.036***,0.031***,0.045***,-0.005,-0.014,0.004,0.031*,-0.002,0.026,-0.043*,-0.052**,-0.006,-0.074**,-0.079**,0.007
PD_grassland,0.026***,0.019***,0.051***,-0.006,-0.023**,0.027*,0.089***,-0.052**,-0.129***,0.116***,0.083**,0.174***,0.126***,0.078*,-0.074*
PD_tree_cover,-0.447***,-0.442***,-0.461***,-0.423***,-0.422***,-0.455***,-0.416***,-0.422***,-0.489***,-0.415***,-0.430***,-0.487***,-0.424***,-0.421***,-0.497***
PD_water,-0.331***,-0.323***,-0.352***,-0.171***,-0.160***,-0.211***,-0.110***,-0.098***,-0.182***,-0.125***,-0.109***,-0.183***,-0.144***,-0.118***,-0.210***
PD_wetland,-0.035***,-0.023***,-0.064***,-0.055***,-0.038***,-0.090***,-0.056***,-0.021,NaN,-0.087***,-0.073***,NaN,0.079**,-0.018,NaN
SHDI,nan,NaN,NaN,0.247***,0.248***,0.250***,0.245***,0.178***,0.096***,NaN,NaN,NaN,NaN,NaN,NaN
isa_fraction,0.592***,0.575***,0.618***,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
_Model_R2,0.693,0.709,0.668,0.752,0.765,0.731,0.765,0.775,0.747,0.757,0.765,0.756,0.746,0.753,0.751

In [4]:
vif_result

,,Zone_15,Zone_26,Global.1,Zone_15.1,Zone_26.1,Global.2,Zone_15.2,Zone_26.2,Global.3,Zone_15.3,Zone_26.3,Global.4,Zone_15.4,Zone_26.4
Subset_Scale,Global,,,,,,,,,,,,,,
Grid_Resolution,100m,100m,100m,250m,250m,250m,500m,500m,500m,750m,750m,750m,1000m,1000m,1000m
PLAND_tree_cover,5.340900510689371,5.56465084732252,5.742387912628028,3.2005769898809575,3.2847623945878732,3.300499530517762,4.311927096559532,4.274946965731926,4.7592615782061705,4.95436724186528,4.955822636036767,5.660510192606679,5.555947277540163,5.404529247445762,6.498450652291453
building_height_mean,2.1506972687135186,2.2165365277495,2.0328726153876984,2.4305696977294446,2.7731073254918077,2.48867564052263,2.964182309930073,3.385631216190645,3.113248221224147,3.273768433688224,3.861296883304187,3.5173261918850383,3.3043965551570036,3.9870403073006098,3.6712870950417433
pop_sum,1.8662476134111636,1.9889305444918777,1.703804376337569,1.9820297947765098,2.2909025274953994,1.752029723616261,2.252307800627077,2.733012988145653,1.9255251388422239,2.352626535281963,3.056358902277466,2.0243005758803,2.4293891547945172,3.105572006902894,2.135688470409028
ED_tree_cover,2.9778810996933824,2.820695913691947,3.075625039275401,4.682483904593224,4.5807115292729295,4.480081941462377,4.489717382159854,4.364606059516251,4.184525023620675,3.82291961571167,4.3647773881663765,3.514232411720818,4.188686624188291,4.219310843542898,4.340165142564834
BCR,4.190593574177632,4.5020392910563976,3.9776553579045846,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CONTAG,1.1671527880851147,1.165576964055135,1.1644692592866976,1.4609908940997975,1.4586354259264493,1.4724257227721202,2.3351972806424874,2.544039885357394,2.1601609706338545,2.189946130368063,2.467708562818315,2.063577623633022,2.5245168747749855,2.4316682527901117,2.8126594609343627
ED_bare_land,nan,NaN,NaN,NaN,NaN,NaN,4.620176187661048,4.972976333009859,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ED_cropland,3.081559021485682,3.110390216105056,2.8599911751785863,3.705444875708418,3.9855104509008834,3.7755167105344065,4.558457097928506,4.321368572939744,4.320015077384325,NaN,NaN,NaN,NaN,NaN,NaN
ED_grassland,3.589692674640249,3.54891702529185,3.475611724348057,4.543969962844582,4.666377378363688,4.319679225425308,4.844885883003366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ED_water,2.791537337099933,2.6897853977999984,2.9032757065787913,3.2177788752712773,3.2410384628389335,3.2298694200780904,3.128769399075681,3.154656049537322,2.9232643057806613,2.722545287970287,2.880549911090039,2.4842756915449855,4.082507713041272,4.011096578889951,2.4690384147306177
ED_wetland,3.757939644112928,2.6697506002233062,NaN,NaN,NaN,3.5290445249912517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LPI_bare_land,1.2959723041637845,1.2829587264122673,1.359748744379812,1.4478141531741033,1.2735130062956594,1.5021905788248437,2.2912900077991583,2.592849374354771,1.209910899019278,1.2052437711400286,1.3320191943787718,1.151662367929883,1.2106090474811138,1.2445340683532033,1.2140377331688994
LPI_cropland,3.3564021390856444,3.5393000130655055,3.314600982831386,2.5673614007348338,2.6932461883513463,2.629537226298838,3.2740207416182465,3.1236758531016164,3.2193277723897764,2.3993133875333394,2.501318482676997,2.623369412171958,2.614923532571768,2.54588956746825,2.9330278112924244
LPI_grassland,3.0921199035754,3.381039557535316,3.203643058116946,2.3966420215334487,2.4824550914400714,2.247676525958442,2.451075494378069,2.016877166207151,2.064674108076652,1.996825161177074,2.049463438958811,2.0175077245976785,2.1004283682178255,2.128260768046145,2.128823167683469
LPI_shrubland,1.0036935900696877,NaN,NaN,1.0152469931581591,1.0015529607888458,NaN,1.966555421419412,NaN,1.0023892212807914,1.6152132011854767,1.5361563117603914,1.0020644196275121,1.6177512456767305,1.6207483371878892,1.0041268680814812
LPI_water,3.1468562607499755,3.529724801588713,2.7903375044328143,1.9215631335819792,2.0572770089349195,1.8387496049309562,2.056625873999695,2.244156413862269,2.0088210502487884,2.163388285481673,2.270806324158022,2.1393454242639813,2.1487397498870418,2.2335687394731853,2.0998668670658254
LPI_wetland,1.558893958342437,1.4577022645149549,1.527656099485626,1.4356228502100739,1.4537570399000384,2.0341210268503906,1.2595239977935146,1.2552376785964614,1.4116903696379288,1.2435924223016086,1.244862696741761,1.4470462275248712,1.3569261352695505,1.2324280483630867,1.6242384887383707
LSI_bare_land,nan,NaN,NaN,4.3271569205253195,NaN,4.669267193362605,2.983428058924975,2.9577878942747247,NaN,3.506918789516823,4.004791175981103,3.6505665241671896,NaN,NaN,4.722167666452826
LSI_cropland,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.746337447440253,2.7909893820318965,3.227352027858201,3.80646981069118,3.7240158287949714,3.550076376453246
LSI_grassland,nan,NaN,NaN,NaN,NaN,NaN,NaN,4.183753834066595,NaN,4.094979446404765,4.269762518882532,4.066526876928722,4.800066469123606,4.592080003717896,NaN
LSI_shrubland,nan,NaN,NaN,NaN,NaN,NaN,1.969575141780398,1.0034705459710236,NaN,1.6185673154343867,1.5411722716704706,NaN,1.621763991244888,1.627196086085419,NaN
LSI_water,nan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.2688044045067794,3.91923683411329,NaN
LSI_wetland,nan,NaN,NaN,NaN,NaN,NaN,NaN,4.487627300914612,1.48410225052927,NaN,NaN,1.5852708832006908,4.752872959456385,NaN,1.8102926498641225
PD_bare_land,1.3260207688424481,1.3278888292391462,1.3843305024549208,4.102006689735817,1.285747599792669,4.222987477593868,NaN,NaN,1.3551217648114005,3.182205774959995,3.4608171311816687,3.4233348769139242,1.453963059723369,1.494414204132025,4.397438559973103
PD_built_up,2.01046945770107,1.8842733353837156,2.0449114057951356,2.0185227326133224,2.039298695093238,1.9271138390644462,2.217996180666999,2.056143188247392,2.1677365630626277,2.2179916631785987,2.360232505963243,2.1020240254918776,2.183163273074705,2.1610901918132464,2.4058495896412615
PD_cropland,3.8518145459654547,3.796617261049935,3.522824786604979,2.6688557913735487,2.8470665032742755,2.5819951380677777,2.6246557336072467,2.519444203664649,2.4541486231258665,2.2964363322452237,2.227518160183786,2.9141436755260144,3.322198597481197,3.283862431455775,3.161800011849178
PD_grassland,2.8886117834545577,2.832844856805554,2.8083349331585583,2.722405668243463,2.7186853981936614,2.522412313809677,2.9589796454297814,3.8156350916545088,1.6738127657778352,3.9680664235272336,3.999839102005017,4.13434006219007,4.507125165745238,4.465014032985938,1.8537338727023818
PD_tree_cover,2.059910215276762,1.8811288722762842,2.0600347712827274,2.3560724011443934,2.379421767546127,2.326784085904903,2.8388170655905354,2.6576342159226916,2.9707258521932434,3.0282210755481644,3.082494715896914,3.308971233656828,3.366053433578598,3.110468606217791,3.9629646567221957
PD_water,4.417123300097853,4.673630362631197,4.059979323656174,2.609577288118145,2.645268786042185,2.4996992923191232,2.1471273160526128,2.028447607990457,1.9982967192768377,1.969131727351821,2.0474508148853054,1.8484659813110882,2.3736006927190227,2.233899464820589,1.8635616582390286
PD_wetland,3.1735206811173864,2.3983675892381835,1.5435051945161076,1.4821292668417738,1.5090458681419006,2.178719112166035,1.3197755009984726,4.194311033293415,NaN,1.3243516362581178,1.3739387080240015,NaN,4.107796005132594,1.3542023138955976,NaN
SHDI,nan,NaN,NaN,4.208036071202652,3.8854604224852634,4.340393425771459,4.231193930286864,4.090122243480866,3.9536457294101393,NaN,NaN,NaN,NaN,NaN,NaN
isa_fraction,4.318352663300108,4.173383428284412,4.761116711497861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN